import {
  Ban,
  Bold,
  CalendarClock,
  CalendarPlus,
  Check,
  ChevronDown,
  ChevronRight,
  CirclePlus,
  Code,
  Database,
  Download,
  Eye,
  ExternalLink,
  File,
  FileCode2,
  FileInput,
  FilePenLine,
  FileText,
  Film,
  Folder,
  FolderInput,
  FolderOpen,
  FolderPen,
  FolderPlus,
  GripHorizontal,
  GripVertical,
  Heading1,
  History,
  Image,
  ImagePlus,
  Italic,
  Link,
  List,
  ListChecks,
  ListOrdered,
  ListPlus,
  LocateFixed,
  Maximize2,
  Menu,
  Minimize2,
  MoreHorizontal,
  NotebookTabs,
  Paperclip,
  PanelLeft,
  Pencil,
  Quote,
  Redo2,
  RotateCcw,
  Search,
  Settings2,
  Table,
  Trash2,
  Undo2,
  Upload,
  X,
  ZoomIn,
  ZoomOut,
  createElement as createIconElement,
  createIcons,
  type IconNode,
} from "lucide";

const ICONS = {
  Ban,
  Bold,
  CalendarClock,
  CalendarPlus,
  Check,
  ChevronDown,
  ChevronRight,
  CirclePlus,
  Code,
  Database,
  Download,
  Eye,
  ExternalLink,
  File,
  FileCode2,
  FileInput,
  FilePenLine,
  FileText,
  Film,
  Folder,
  FolderInput,
  FolderOpen,
  FolderPen,
  FolderPlus,
  GripHorizontal,
  GripVertical,
  Heading1,
  History,
  Image,
  ImagePlus,
  Italic,
  Link,
  List,
  ListChecks,
  ListOrdered,
  ListPlus,
  LocateFixed,
  Maximize2,
  Menu,
  Minimize2,
  MoreHorizontal,
  NotebookTabs,
  Paperclip,
  PanelLeft,
  Pencil,
  Quote,
  Redo2,
  RotateCcw,
  Search,
  Settings2,
  Table,
  Trash2,
  Undo2,
  Upload,
  X,
  ZoomIn,
  ZoomOut,
} satisfies Record<string, IconNode>;

export type IconName = keyof typeof ICONS;

export function icon(name: IconName, size = 18): SVGElement {
  const svg = createIconElement(ICONS[name], {
    width: size,
    height: size,
    "stroke-width": 2,
    "aria-hidden": "true",
    focusable: "false",
  });
  svg.classList.add("lucide-icon");
  // 与静态 createIcons 路径保持一致，携带 lucide 与 lucide-<name> 类名，便于样式与测试选择。
  svg.classList.add("lucide", `lucide-${kebabCase(name)}`);
  return svg;
}

function kebabCase(value: string): string {
  return value.replace(/([a-z])([A-Z])/g, "$1-$2").replace(/([A-Za-z])(\d)/g, "$1-$2").toLowerCase();
}

export function refreshStaticIcons(root: Element | Document = document): void {
  createIcons({ icons: ICONS, root, attrs: { "aria-hidden": "true", "stroke-width": 2 } });
}
