import { requiredElement } from "./dom.js";

export interface Elements {
  sidebar: HTMLElement;
  sidebarClose: HTMLButtonElement;
  navToggle: HTMLButtonElement;
  taskForm: HTMLFormElement;
  taskTitle: HTMLInputElement;
  taskPriority: HTMLSelectElement;
  taskDueDate: HTMLInputElement;
  taskFolder: HTMLSelectElement;
  taskTag: HTMLInputElement;
  clearForm: HTMLButtonElement;
  newFolder: HTMLButtonElement;
  folderTree: HTMLElement;
  workspaceTitle: HTMLElement;
  taskList: HTMLElement;
  emptyState: HTMLElement;
  searchInput: HTMLInputElement;
  statusFilters: NodeListOf<HTMLButtonElement>;
  viewModes: NodeListOf<HTMLButtonElement>;
  sortMode: HTMLSelectElement;
  metricActive: HTMLElement;
  metricCompleted: HTMLElement;
  metricDiscarded: HTMLElement;
  metricDue: HTMLElement;
  exportData: HTMLButtonElement;
  importData: HTMLButtonElement;
  importFile: HTMLInputElement;
  resetDemo: HTMLButtonElement;
  undoAction: HTMLButtonElement;
  redoAction: HTMLButtonElement;
  themeSelect: HTMLSelectElement;
  taskDetail: HTMLElement;
  detailClose: HTMLButtonElement;
  detailEmpty: HTMLElement;
  detailForm: HTMLFormElement;
  detailTitle: HTMLTextAreaElement;
  detailNotes: HTMLTextAreaElement;
  detailStatus: HTMLSelectElement;
  detailPriority: HTMLSelectElement;
  detailFolder: HTMLSelectElement;
  detailDueDate: HTMLInputElement;
  detailTag: HTMLInputElement;
  detailCreatedAt: HTMLElement;
  detailUpdatedAt: HTMLElement;
  cancelDetail: HTMLButtonElement;
  folderDialog: HTMLDialogElement;
  folderDialogForm: HTMLFormElement;
  folderDialogTitle: HTMLElement;
  folderName: HTMLInputElement;
  folderParent: HTMLSelectElement;
  folderDeleteDialog: HTMLDialogElement;
  folderDeleteText: HTMLElement;
  folderDeleteMove: HTMLButtonElement;
  folderDeleteBranch: HTMLButtonElement;
  folderDeleteCancel: HTMLButtonElement;
  folderDeleteClose: HTMLButtonElement;
  confirmDialog: HTMLDialogElement;
  confirmTitle: HTMLElement;
  confirmText: HTMLElement;
  confirmClose: HTMLButtonElement;
  confirmCancel: HTMLButtonElement;
  confirmOk: HTMLButtonElement;
  toast: HTMLElement;
}

export function queryElements(): Elements {
  return {
    sidebar: requiredElement("#sidebar"),
    sidebarClose: requiredElement("#sidebarClose"),
    navToggle: requiredElement("#navToggle"),
    taskForm: requiredElement("#taskForm"),
    taskTitle: requiredElement("#taskTitle"),
    taskPriority: requiredElement("#taskPriority"),
    taskDueDate: requiredElement("#taskDueDate"),
    taskFolder: requiredElement("#taskFolder"),
    taskTag: requiredElement("#taskTag"),
    clearForm: requiredElement("#clearForm"),
    newFolder: requiredElement("#newFolder"),
    folderTree: requiredElement("#folderTree"),
    workspaceTitle: requiredElement("#workspaceTitle"),
    taskList: requiredElement("#taskList"),
    emptyState: requiredElement("#emptyState"),
    searchInput: requiredElement("#searchInput"),
    statusFilters: document.querySelectorAll<HTMLButtonElement>(".status-segment"),
    viewModes: document.querySelectorAll<HTMLButtonElement>(".view-segment"),
    sortMode: requiredElement("#sortMode"),
    metricActive: requiredElement("#metricActive"),
    metricCompleted: requiredElement("#metricCompleted"),
    metricDiscarded: requiredElement("#metricDiscarded"),
    metricDue: requiredElement("#metricDue"),
    exportData: requiredElement("#exportData"),
    importData: requiredElement("#importData"),
    importFile: requiredElement("#importFile"),
    resetDemo: requiredElement("#resetDemo"),
    undoAction: requiredElement("#undoAction"),
    redoAction: requiredElement("#redoAction"),
    themeSelect: requiredElement("#themeSelect"),
    taskDetail: requiredElement("#taskDetail"),
    detailClose: requiredElement("#detailClose"),
    detailEmpty: requiredElement("#detailEmpty"),
    detailForm: requiredElement("#detailForm"),
    detailTitle: requiredElement("#detailTitle"),
    detailNotes: requiredElement("#detailNotes"),
    detailStatus: requiredElement("#detailStatus"),
    detailPriority: requiredElement("#detailPriority"),
    detailFolder: requiredElement("#detailFolder"),
    detailDueDate: requiredElement("#detailDueDate"),
    detailTag: requiredElement("#detailTag"),
    detailCreatedAt: requiredElement("#detailCreatedAt"),
    detailUpdatedAt: requiredElement("#detailUpdatedAt"),
    cancelDetail: requiredElement("#cancelDetail"),
    folderDialog: requiredElement("#folderDialog"),
    folderDialogForm: requiredElement("#folderDialogForm"),
    folderDialogTitle: requiredElement("#folderDialogTitle"),
    folderName: requiredElement("#folderName"),
    folderParent: requiredElement("#folderParent"),
    folderDeleteDialog: requiredElement("#folderDeleteDialog"),
    folderDeleteText: requiredElement("#folderDeleteText"),
    folderDeleteMove: requiredElement("#folderDeleteMove"),
    folderDeleteBranch: requiredElement("#folderDeleteBranch"),
    folderDeleteCancel: requiredElement("#folderDeleteCancel"),
    folderDeleteClose: requiredElement("#folderDeleteClose"),
    confirmDialog: requiredElement("#confirmDialog"),
    confirmTitle: requiredElement("#confirmTitle"),
    confirmText: requiredElement("#confirmText"),
    confirmClose: requiredElement("#confirmClose"),
    confirmCancel: requiredElement("#confirmCancel"),
    confirmOk: requiredElement("#confirmOk"),
    toast: requiredElement("#toast"),
  };
}
