import { requiredElement } from "./dom.js";

export interface Elements {
  taskForm: HTMLFormElement;
  taskTitle: HTMLTextAreaElement;
  taskPriority: HTMLSelectElement;
  taskDueDate: HTMLInputElement;
  taskTag: HTMLInputElement;
  clearForm: HTMLButtonElement;
  taskList: HTMLElement;
  emptyState: HTMLElement;
  taskTemplate: HTMLTemplateElement;
  searchInput: HTMLInputElement;
  filters: NodeListOf<HTMLButtonElement>;
  metricOpen: HTMLElement;
  metricDone: HTMLElement;
  metricDue: HTMLElement;
  doneLog: HTMLElement;
  nextPlan: HTMLElement;
  addDoneItem: HTMLButtonElement;
  addNextItem: HTMLButtonElement;
  feedbackInput: HTMLTextAreaElement;
  applyFeedback: HTMLButtonElement;
  iterationHistory: HTMLElement;
  iterationCount: HTMLElement;
  currentIterationTitle: HTMLElement;
  completeIteration: HTMLButtonElement;
  exportData: HTMLButtonElement;
  importData: HTMLButtonElement;
  importFile: HTMLInputElement;
  resetDemo: HTMLButtonElement;
  undoAction: HTMLButtonElement;
  redoAction: HTMLButtonElement;
  themeSelect: HTMLSelectElement;
  taskDialog: HTMLDialogElement;
  taskDialogForm: HTMLFormElement;
  taskDialogTitle: HTMLElement;
  dialogTaskTitle: HTMLTextAreaElement;
  dialogTaskPriority: HTMLSelectElement;
  dialogTaskDueDate: HTMLInputElement;
  dialogTaskTag: HTMLInputElement;
  itemDialog: HTMLDialogElement;
  itemDialogForm: HTMLFormElement;
  itemDialogTitle: HTMLElement;
  itemDialogLabel: HTMLElement;
  itemDialogText: HTMLTextAreaElement;
  confirmDialog: HTMLDialogElement;
  confirmTitle: HTMLElement;
  confirmText: HTMLElement;
  confirmClose: HTMLButtonElement;
  confirmCancel: HTMLButtonElement;
  confirmOk: HTMLButtonElement;
  toast: HTMLElement;
}

export function queryElements(): Elements {
  return {
    taskForm: requiredElement("#taskForm"),
    taskTitle: requiredElement("#taskTitle"),
    taskPriority: requiredElement("#taskPriority"),
    taskDueDate: requiredElement("#taskDueDate"),
    taskTag: requiredElement("#taskTag"),
    clearForm: requiredElement("#clearForm"),
    taskList: requiredElement("#taskList"),
    emptyState: requiredElement("#emptyState"),
    taskTemplate: requiredElement("#taskTemplate"),
    searchInput: requiredElement("#searchInput"),
    filters: document.querySelectorAll<HTMLButtonElement>(".segment"),
    metricOpen: requiredElement("#metricOpen"),
    metricDone: requiredElement("#metricDone"),
    metricDue: requiredElement("#metricDue"),
    doneLog: requiredElement("#doneLog"),
    nextPlan: requiredElement("#nextPlan"),
    addDoneItem: requiredElement("#addDoneItem"),
    addNextItem: requiredElement("#addNextItem"),
    feedbackInput: requiredElement("#feedbackInput"),
    applyFeedback: requiredElement("#applyFeedback"),
    iterationHistory: requiredElement("#iterationHistory"),
    iterationCount: requiredElement("#iterationCount"),
    currentIterationTitle: requiredElement("#currentIterationTitle"),
    completeIteration: requiredElement("#completeIteration"),
    exportData: requiredElement("#exportData"),
    importData: requiredElement("#importData"),
    importFile: requiredElement("#importFile"),
    resetDemo: requiredElement("#resetDemo"),
    undoAction: requiredElement("#undoAction"),
    redoAction: requiredElement("#redoAction"),
    themeSelect: requiredElement("#themeSelect"),
    taskDialog: requiredElement("#taskDialog"),
    taskDialogForm: requiredElement("#taskDialogForm"),
    taskDialogTitle: requiredElement("#taskDialogTitle"),
    dialogTaskTitle: requiredElement("#dialogTaskTitle"),
    dialogTaskPriority: requiredElement("#dialogTaskPriority"),
    dialogTaskDueDate: requiredElement("#dialogTaskDueDate"),
    dialogTaskTag: requiredElement("#dialogTaskTag"),
    itemDialog: requiredElement("#itemDialog"),
    itemDialogForm: requiredElement("#itemDialogForm"),
    itemDialogTitle: requiredElement("#itemDialogTitle"),
    itemDialogLabel: requiredElement("#itemDialogLabel"),
    itemDialogText: requiredElement("#itemDialogText"),
    confirmDialog: requiredElement("#confirmDialog"),
    confirmTitle: requiredElement("#confirmTitle"),
    confirmText: requiredElement("#confirmText"),
    confirmClose: requiredElement("#confirmClose"),
    confirmCancel: requiredElement("#confirmCancel"),
    confirmOk: requiredElement("#confirmOk"),
    toast: requiredElement("#toast"),
  };
}
