<template>
  <dialog id="folderDialog" class="modal"><form id="folderDialogForm" class="modal-card stack"><div class="modal-head"><h2 id="folderDialogTitle">新建文件夹</h2><button class="icon-button" type="button" data-close-dialog aria-label="关闭"><i data-lucide="x"></i></button></div><label class="field"><span>名称</span><input id="folderName" type="text" maxlength="48" required /></label><label class="field"><span>上级文件夹</span><select id="folderParent"></select></label><div class="modal-actions"><button class="button ghost" type="button" data-close-dialog>取消</button><button class="button primary" type="submit">保存</button></div></form></dialog>
  <dialog id="folderMoveDialog" class="modal"><form id="folderMoveForm" class="modal-card stack"><div class="modal-head"><h2>移动文件夹</h2><button class="icon-button" type="button" data-close-dialog aria-label="关闭"><i data-lucide="x"></i></button></div><p id="folderMoveName" class="confirm-text"></p><label class="field"><span>目标上级</span><select id="folderMoveParent"></select></label><label class="field"><span>同级位置</span><select id="folderMovePosition"></select></label><div class="modal-actions"><button class="button ghost" type="button" data-close-dialog>取消</button><button class="button primary" type="submit">确认移动</button></div></form></dialog>
  <dialog id="folderDeleteDialog" class="modal"><form class="modal-card stack"><div class="modal-head"><h2>删除非空文件夹</h2><button class="icon-button" id="folderDeleteClose" type="button" aria-label="关闭"><i data-lucide="x"></i></button></div><p id="folderDeleteText" class="confirm-text"></p><div class="choice-actions"><button class="button secondary" id="folderDeleteMove" type="button">内容移到上一级</button><button class="button danger-button" id="folderDeleteBranch" type="button">删除整个分支</button><button class="button ghost" id="folderDeleteCancel" type="button">取消</button></div></form></dialog>
  <dialog id="confirmDialog" class="modal"><form class="modal-card stack"><div class="modal-head"><h2 id="confirmTitle">确认操作</h2><button class="icon-button" id="confirmClose" type="button" aria-label="关闭"><i data-lucide="x"></i></button></div><p id="confirmText" class="confirm-text"></p><div class="modal-actions"><button class="button ghost" id="confirmCancel" type="button">取消</button><button class="button primary" id="confirmOk" type="button">确认</button></div></form></dialog>
  <dialog id="conflictDialog" class="modal"><form class="modal-card stack"><div class="modal-head"><h2>检测到外部修改</h2><button class="icon-button" id="conflictClose" type="button" aria-label="关闭"><i data-lucide="x"></i></button></div><p id="conflictText" class="confirm-text"></p><div class="conflict-actions"><button class="button primary" id="conflictReload" type="button">重新加载外部版本</button><button class="button secondary" id="conflictCopy" type="button">保存当前内容为冲突副本</button><button class="button ghost" id="conflictCancel" type="button">取消保存</button></div></form></dialog>

  <dialog id="moveDialog" class="modal"><form id="moveDialogForm" class="modal-card stack"><div class="modal-head"><h2>更多任务操作</h2><button class="icon-button" type="button" data-close-dialog aria-label="关闭"><i data-lucide="x"></i></button></div><p id="moveRestriction" class="field-note" hidden>逾期任务改期后可调整文件夹、优先级和顺序。</p><label class="field"><span>目标文件夹</span><select id="moveFolder"></select></label><label class="field"><span>优先级</span><select id="movePriority"><option value="high">高</option><option value="low">低</option></select></label><div class="move-step-actions"><button class="button secondary" id="movePrevious" type="button">移到上一项</button><button class="button secondary" id="moveNext" type="button">移到下一项</button></div><button class="button danger-button" id="moveDelete" type="button"><i data-lucide="trash-2"></i><span>删除任务</span></button><div class="modal-actions"><button class="button ghost" type="button" data-close-dialog>取消</button><button class="button primary" id="moveSubmit" type="submit">移动到末尾</button></div></form></dialog>

  <dialog id="rescheduleDialog" class="modal"><form id="rescheduleForm" class="modal-card stack"><div class="modal-head"><h2>重新安排截止日期</h2><button class="icon-button" type="button" data-close-dialog aria-label="关闭"><i data-lucide="x"></i></button></div><div class="preset-grid" role="group" aria-label="日期快捷选项"><button class="button secondary" type="button" data-reschedule-days="1">明天</button><button class="button secondary" type="button" data-reschedule-days="3">3 天后</button><button class="button secondary" type="button" data-reschedule-days="7">7 天后</button></div><label class="field"><span>新日期</span><input id="rescheduleDate" type="date" required /></label><label class="field"><span>原因</span><input id="rescheduleReason" type="text" maxlength="120" placeholder="可选" /></label><div class="modal-actions"><button class="button ghost" type="button" data-close-dialog>取消</button><button class="button primary" type="submit">确认改期</button></div></form></dialog>

  <dialog id="attachmentRenameDialog" class="modal"><form id="attachmentRenameForm" class="modal-card stack"><div class="modal-head"><h2>重命名附件</h2><button class="icon-button" type="button" data-close-dialog aria-label="关闭"><i data-lucide="x"></i></button></div><label class="field"><span>文件名</span><input id="attachmentRenameName" type="text" maxlength="160" required /></label><div class="modal-actions"><button class="button ghost" type="button" data-close-dialog>取消</button><button class="button primary" type="submit">保存</button></div></form></dialog>
</template>

<style scoped>
.modal-card {
  contain: layout paint;
}
</style>
